### ISSUE TITLE
nondango display contrast

### ISSUE THREAD

**Issue by tckmn** [robx/pzprjs#191]
Currently, it is almost impossible for me to tell which cells and regions are shaded in Nondango.

Could the contrast of the shaded cells be increased?

**Comment by robx** [comment]
By shading, I guess you mean the (auto)-completion shading?

There's even two subtly different shades of light blue here, where the manually entered one seems a bit darker than the autocomplete-shading. (LITS and/or Nori-nori used to have the same difference -- there it got a lot clearer by moving to dots for the manually marked cells, but we can't really do that here.)

Part of the issue seems to be that the circles only leave so little space for the shading... Perhaps there's a better approach to be found here, such as

- also shading the inside of white circles
- only shading the inside of white circles
- having a two-level thing as in Nori-nori after all where we mark the definitely-white-circles with a dot or something

**Comment by robx** [comment]
Moved this over to #1.
