### ISSUE TITLE
Add CI to serve a preview build on pull requests

### ISSUE THREAD

**Issue by robx** [robx/pzprjs#238]
It should be reasonably straightforward to serve up a static preview of a pull request for testing. I.e., what should happen is:

- on pull request, CI runs `make` (as it already does in the test workflow)
- the `dist` folder gets stored somewhere, and a link is added to the PR (probably as a PR comment)

**Comment by x-sheep** [comment]
While I haven't used this myself, [Vercel](https://vercel.com/) offers this. If we don't want to replace the entire server infrastructure, it might be worth it to enable this only for Pull Requests. It's free for open source projects.

Using their `serve` commandline tool does reveal a problem with redirects, where renaming `p.html?puzzleid` to `p` drops the entire query string. This could be fixed by consistently changing all href's in the project to never use `.html`.

**Comment by robx** [comment]
Oh, that was easy, thanks!
