### ISSUE TITLE
Vercel Preview deployment issues

### ISSUE THREAD

**Issue by x-sheep** [robx/pzprjs#288]
Two problems have popped up inside preview deployments after stripping out the Vercel-specific code when merging with pzprxs.
* There is no index.html, meaning there is no meaningful place to start.
* List links are broken, since it doesn't serve pages at `p` anymore, but requires `p.html`.

**Comment by robx** [comment]
It's a bit redundant to keep them around, but feel free to restore those files if there's no obvious better way to fix this. I mostly removed them because I wanted to make sure they don't get in the way when deploying on puzz.link, and because it seemed the easiest way to cut down the amount of changes a bit.

**Comment by x-sheep** [comment]
I'll think of a fix that takes effect only on Vercel deployments, and not when building a deployment.
